### ISSUE TITLE
The channel dimension of the inputs should be defined

### ISSUE THREAD

**Issue by jianing-li** [liruihui/PU-GAN#7]
File "pu_gan.py", line 47, in <module>
    tf.app.run()
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "pu_gan.py", line 43, in main
    run()
  File "pu_gan.py", line 37, in run
    model.train()
  File "/home/ljn/point_process/pugan_iccv2019/Upsampling/model.py", line 122, in train
    self.build_model()
  File "/home/ljn/point_process/pugan_iccv2019/Upsampling/model.py", line 42, in build_model
    self.G_y = self.G(self.input_x)
  File "/home/ljn/point_process/pugan_iccv2019/Upsampling/generator.py", line 25, in __call__
    H = ops.up_projection_unit(features, self.up_ratio_real, scope="up_projection_unit", is_training=self.is_training, bn_decay=None)
  File "/home/ljn/point_process/pugan_iccv2019/Common/ops.py", line 152, in up_projection_unit
    L0 = down_block(H0,up_ratio,is_training=is_training,bn_decay=bn_decay,scope='down_0')
  File "/home/ljn/point_process/pugan_iccv2019/Common/ops.py", line 86, in down_block
    scope='conv1', bn_decay=bn_decay)
  File "/home/ljn/point_process/pugan_iccv2019/Common/ops.py", line 367, in conv2d
    use_bias=use_bias,reuse=None)
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 427, in conv2d
    return layer.apply(inputs)
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 774, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 329, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 696, in __call__
    self.build(input_shapes)
  File "/home/ljn/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/convolutional.py", line 149, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by NaCl96** [comment]
Have you solved the problem?

**Comment by liruihui** [comment]
Sorry, I have no idea about your problem. :(

Ruihui Li

**Comment by liruihui** [comment]
![image](https://user-images.githubusercontent.com/31917103/69843769-eb9b1580-12a3-11ea-9461-02cb7a252ba4.png)

I do not find the same issue.  :(

Ruihui Li

**Comment by xiaoxiaobozb** [comment]
Traceback (most recent call last):
  File "pu_gan.py", line 49, in <module>
    tf.app.run()
  File "/home/luoqibin/Envs/zg/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "pu_gan.py", line 45, in main
    run()
  File "pu_gan.py", line 39, in run
    model.train()
  File "/home/luoqibin/zg/PU-GAN/Upsampling/model.py", line 122, in train
    self.build_model()
  File "/home/luoqibin/zg/PU-GAN/Upsampling/model.py", line 42, in build_model
    self.G_y = self.G(self.input_x)
  File "/home/luoqibin/zg/PU-GAN/Upsampling/generator.py", line 25, in __call__
    H = ops.up_projection_unit(features, self.up_ratio_real, scope="up_projection_unit", is_training=self.is_training, bn_decay=None)
  File "/home/luoqibin/zg/PU-GAN/Common/ops.py", line 152, in up_projection_unit
    L0 = down_block(H0,up_ratio,is_training=is_training,bn_decay=bn_decay,scope='down_0')
  File "/home/luoqibin/zg/PU-GAN/Common/ops.py", line 86, in down_block
    scope='conv1', bn_decay=bn_decay)
  File "/home/luoqibin/zg/PU-GAN/Common/ops.py", line 367, in conv2d
    use_bias=use_bias,reuse=None)
  File "/home/luoqibin/Envs/zg/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 614, in conv2d
    return layer.apply(inputs)
  File "/home/luoqibin/Envs/zg/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 762, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/luoqibin/Envs/zg/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 636, in __call__
    self.build(input_shapes)
  File "/home/luoqibin/Envs/zg/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 132, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by MgGa-zzz** [comment]
I have the same question.......

**Comment by Nhunguts** [comment]
> I have the same question.......

Hi @MgGa-zzz , how many points of the test point cloud? How size of patch you did you use for training?
